# Generated by Django 5.2 on 2025-04-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_remove_market_market_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='plan',
            field=models.CharField(blank=True),
        ),
    ]
