# Generated by Django 5.2 on 2025-04-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_market_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='profile_picture',
            field=models.ImageField(blank=True, default='404-BNF.jpg', null=True, upload_to='profiles/'),
        ),
    ]
