# Generated by Django 5.2 on 2025-04-30 00:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_alter_market_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar image'),
        ),
    ]
