# Generated by Django 5.2 on 2025-06-05 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_alter_market_profile_picture'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Debtors', to='markets.market')),
            ],
        ),
    ]
