# Generated by Django 5.2 on 2025-06-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_debtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expanse',
            name='type',
            field=models.CharField(choices=[('salary', 'Maosh'), ('rent', 'Ijara'), ('tax', 'Soliq'), ('ad', 'Reklama'), ('other', 'Boshqa')], default='salary', max_length=10),
        ),
    ]
