# Generated by Django 5.2 on 2025-06-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_expanse_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expanse',
            name='type',
            field=models.CharField(choices=[('salary', 'Maosh'), ('rent', 'Ijara'), ('tax', 'Soliq'), ('ad', 'Reklama'), ('licence', 'Litsenziya'), ('communal', "Komunal to'lovlar"), ('other', 'Boshqa')], default='salary', max_length=10),
        ),
    ]
