# Generated by Django 5.2 on 2025-06-15 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_alter_market_profile_picture'),
        ('reports', '0005_rename_expanse_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='market_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expenses', to='markets.market'),
        ),
    ]
