# Generated by Django 5.2 on 2025-04-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('mass', 'Grammda'), ('numeric', 'Sonda')], default='numeric', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ended', 'Tugagan'), ('few', 'Kam qolgan'), ('available', 'Mavjud')], default='ended', max_length=15),
        ),
    ]
