# Generated by Django 5.2 on 2025-06-02 02:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='sstore_products/0c32b31941863a0f1fb8e97eaf55f595_lc10im', max_length=255, verbose_name='product image'),
        ),
    ]
