# Generated by Django 5.2 on 2025-06-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('kg', 'KG'), ('dona', 'DONA'), ('metr', 'METR'), ('litr', 'LITR')], default='dona', max_length=10),
        ),
    ]
