# Generated by Django 5.2 on 2025-06-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_quantity_type'),
        ('reports', '0002_debtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productupdate',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='reports.debtor'),
        ),
    ]
